@Relay.Api_HostAddress = http://localhost:5030

GET {{Relay.Api_HostAddress}}/weatherforecast/
Accept: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiYmxvZ2FkbWluIiwianRpIjoiMTIiLCJUZW5hbnRJZCI6IjAiLCJpYXQiOiIxNzIxMTI3MzI5IiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9leHBpcmF0aW9uIjoiMjAyNC83LzE2IDExOjU1OjI5IiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiU3VwZXJBZG1pbiIsIm5iZiI6MTcyMTA5ODUzMCwiZXhwIjoxNzIxMTAyMTMwLCJpc3MiOiJCbG9nLkNvcmUiLCJhdWQiOiJ3ciJ9.UaMcXuY2h_9_Ld11aNdgYW6_Jkt6EdC1jxGZPdIU9L0

### Authorization:Bearer 有过期时间，调试需要重新生成

POST {{Relay.Api_HostAddress}}/weatherforecast/
Accept: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiYmxvZ2FkbWluIiwianRpIjoiMTIiLCJUZW5hbnRJZCI6IjAiLCJpYXQiOiIxNzIxMTI3MzI5IiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9leHBpcmF0aW9uIjoiMjAyNC83LzE2IDExOjU1OjI5IiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiU3VwZXJBZG1pbiIsIm5iZiI6MTcyMTA5ODUzMCwiZXhwIjoxNzIxMTAyMTMwLCJpc3MiOiJCbG9nLkNvcmUiLCJhdWQiOiJ3ciJ9.UaMcXuY2h_9_Ld11aNdgYW6_Jkt6EdC1jxGZPdIU9L0

###

GET {{Relay.Api_HostAddress}}/api/Log/
Accept: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiYmxvZ2FkbWluIiwianRpIjoiMTIiLCJUZW5hbnRJZCI6IjAiLCJpYXQiOiIxNzIxMTI3MzI5IiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9leHBpcmF0aW9uIjoiMjAyNC83LzE2IDExOjU1OjI5IiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiU3VwZXJBZG1pbiIsIm5iZiI6MTcyMTA5ODUzMCwiZXhwIjoxNzIxMTAyMTMwLCJpc3MiOiJCbG9nLkNvcmUiLCJhdWQiOiJ3ciJ9.UaMcXuY2h_9_Ld11aNdgYW6_Jkt6EdC1jxGZPdIU9L0

### Authorization:Bearer 有过期时间，调试需要重新生成

POST {{Relay.Api_HostAddress}}/api/Log/
Accept: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiYmxvZ2FkbWluIiwianRpIjoiMTIiLCJUZW5hbnRJZCI6IjAiLCJpYXQiOiIxNzIxMTI3MzI5IiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9leHBpcmF0aW9uIjoiMjAyNC83LzE2IDExOjU1OjI5IiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiU3VwZXJBZG1pbiIsIm5iZiI6MTcyMTA5ODUzMCwiZXhwIjoxNzIxMTAyMTMwLCJpc3MiOiJCbG9nLkNvcmUiLCJhdWQiOiJ3ciJ9.UaMcXuY2h_9_Ld11aNdgYW6_Jkt6EdC1jxGZPdIU9L0

### 
